#' Bat pun phrases used in say()

phrases <-  c(
  "The first thing bats learn in school is the alphaBAT",
  "What is a bat's favourite sport?        ACROBATICS",
  "What is a bat's favourite sport?        BATMINTON",
  "Just hang in there",
  "Where do vampire bats keep their money? The blood bank",
  "I’m a huge fang of bat puns",
  "How do bats decide where they roost?        Fang Shui",
  "I’m batty for you!",
  "Things are getting from bat to worse!",
  "Always aim for suck-cess!",
  "Con-bat-tulations!",
  "What do you call a nimble bat?        An ACROBAT",
  "What is a bat's favourite TV show?        The BATchelor",
  "Good job! You deserve a bat on the back!",
  "Hi, I'm Bat-thew McConaughey",
  "Why couldn't Maureen play with her toys on Christmas?        The BATteries were not included",
  "What’s a bats favorite desert?        Fly-scream",
  "What is a bat’s favorite spice?        Oreguano",
  "What’s a bat’s favorite dessert?        Upside down cake",
  "I saw a bat fly today. It hit a home-run",
  "Batman is a fruit bat. I saw him eating a bananananananananananananana!",
  "What three things are most important to bats about their local real estate?        Echolocation Echolocation Echolocation",
  "Did you hear about the bat/donkey hybrid? It's pretty bat-ass!",
  "What do bats study for at University?        Their BATchelor",
  "What did the bat give to it's chickens?        HENdra",
  "Did you hear about the vampire bat artist - Vincent Vein Gogh?",
  "Anything they can do, you can do bat-ter",
  "I love Lady Gaga's new song - Bat romance",
  "Do you want the good news or the bat news?",
  "Let me show you my bat-chelor pad..."
)
